### ISSUE TITLE
По запросу "ев" находятся "ели".

### ISSUE THREAD

**Issue by un1t** [AKuznetsov/russianmorphology#3]
Добрый день!

Я использую плагин для elasticsearch - analysis-morphology который, как я понимаю, использует вашу библиотеку:
И с ней проиходит такая интересная штука
"ели" - генерирует токены "ель", "есть".
"ев" - генерирует токены "ева", "есть".

https://github.com/imotov/elasticsearch-analysis-morphology/issues/19

**Comment by AKuznetsov** [comment]
Ев это прошедшее время от глагола есть пример "Ев это пирог я думало о морфологии"
Ев это множественное число родительный падеж от Ева  пример "Евы собрались на собрание тезок, но многих Ев не было по причине болезни."

**Comment by un1t** [comment]
Действительно, спасибо за разьяснения!
